/**
 * Compiles the contracts with solc-js (bundled in the npm package, so no Foundry or downloads
 * needed) and writes their ABIs to packages/shared/src/abi.ts for the server and web app.
 * Foundry stays the test runner (CI); both use the same compiler version and settings.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Abi, Hex } from 'viem';

const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-require-imports
const solc = require('solc') as { compile(input: string, opts: object): string };

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTRACTS = ['GameToken', 'GameVault'] as const;
export type ContractName = (typeof CONTRACTS)[number];
export type Artifacts = Record<ContractName, { abi: Abi; bytecode: Hex }>;

function findImport(path: string): { contents: string } | { error: string } {
  const candidates = [join(root, path), join(root, 'node_modules', path)];
  for (const file of candidates) {
    try {
      return { contents: readFileSync(file, 'utf8') };
    } catch {
      // try the next location
    }
  }
  return { error: `not found: ${path}` };
}

export function compile(): Artifacts {
  const input = {
    language: 'Solidity',
    sources: Object.fromEntries(
      CONTRACTS.map((name) => [
        `src/${name}.sol`,
        { content: readFileSync(join(root, 'src', `${name}.sol`), 'utf8') },
      ]),
    ),
    settings: {
      // Matches foundry.toml.
      optimizer: { enabled: true, runs: 200 },
      evmVersion: 'shanghai',
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
    },
  };
  const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImport })) as {
    errors?: { severity: string; formattedMessage: string }[];
    contracts: Record<string, Record<string, { abi: Abi; evm: { bytecode: { object: string } } }>>;
  };
  const errors = (output.errors ?? []).filter((e) => e.severity === 'error');
  if (errors.length) throw new Error(errors.map((e) => e.formattedMessage).join('\n'));
  return Object.fromEntries(
    CONTRACTS.map((name) => {
      const c = output.contracts[`src/${name}.sol`]![name]!;
      return [name, { abi: c.abi, bytecode: `0x${c.evm.bytecode.object}` as Hex }];
    }),
  ) as Artifacts;
}

function writeAbis(artifacts: Artifacts): string {
  const file = join(root, '..', 'shared', 'src', 'abi.ts');
  const body = CONTRACTS.map(
    (name) =>
      `export const ${name[0]!.toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifacts[name].abi, null, 2)} as const;`,
  ).join('\n\n');
  writeFileSync(
    file,
    `// Generated by packages/contracts/scripts/compile.ts. Do not edit; run pnpm compile:contracts.\n\n${body}\n`,
  );
  return file;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const file = writeAbis(compile());
  console.log(`Compiled ${CONTRACTS.join(', ')}; ABIs written to ${file}`);
}
